version: 2

sources:
  - name: bigquery_source
    schema: ReviewInsight

    tables:
      - name: GuestRelation_ReviewAnalysis

models:
    - name: GuestRelationReviewAnalysis
      description: "Last insertion of all reviews"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null