
version: 2

models:
    - name: GuestRelationReviewAnalysis
      description: "last insertion des reviews"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null